export const ALUMNI_MOCK_DATA = [
  {
    id: 1,
    name: "Ahmed Khan",
    email: "ahmed.khan@gmail.com",
    phone: "+92 300 1234567",
    graduationYear: "2018",
    department: "Computer Science",
    currentPosition: "Senior Software Engineer",
    company: "Google",
    location: "San Francisco, USA",
    expertise: ["Machine Learning", "Cloud Computing", "React"],
    previousCompanies: [
      {
        companyName: "Microsoft",
        role: "Software Engineer",
        duration: { from: 2018, to: 2020 },
      },
      {
        companyName: "Amazon",
        role: "Junior Developer",
        duration: { from: 2016, to: 2018 },
      },
    ],
    avatar: "AK",
  },
  {
    id: 2,
    name: "Sara Ali",
    email: "sara.ali@outlook.com",
    phone: null,
    graduationYear: "2019",
    department: "Software Engineering",
    currentPosition: "Product Manager",
    company: "Microsoft",
    location: "Seattle, USA",
    expertise: ["Product Strategy", "Agile", "UX Design"],
    previousCompanies: [
      {
        companyName: "Facebook",
        role: "Associate PM",
        duration: { from: 2019, to: 2021 },
      },
    ],
    avatar: "SA",
  },
  {
    id: 3,
    name: "Hassan Raza",
    email: "hassan.raza@yahoo.com",
    phone: "+971 50 9876543",
    graduationYear: "2020",
    department: "Computer Science",
    currentPosition: "Tech Lead",
    company: "Amazon",
    location: "Dubai, UAE",
    expertise: ["Full Stack", "DevOps", "AWS"],
    previousCompanies: [
      {
        companyName: "Careem",
        role: "Senior Developer",
        duration: { from: 2020, to: 2022 },
      },
      {
        companyName: "Systems Limited",
        role: "Software Engineer",
        duration: { from: 2018, to: 2020 },
      },
    ],
    avatar: "HR",
  },
  {
    id: 4,
    name: "Fatima Hussain",
    email: "fatima.h@gmail.com",
    phone: "+1 408 5551234",
    graduationYear: "2017",
    department: "Electrical Engineering",
    currentPosition: "Hardware Engineer",
    company: "Intel",
    location: "California, USA",
    expertise: ["VLSI Design", "Embedded Systems", "IoT"],
    previousCompanies: [
      {
        companyName: "Qualcomm",
        role: "Hardware Engineer",
        duration: { from: 2017, to: 2019 },
      },
    ],
    avatar: "FH",
  },
  {
    id: 5,
    name: "Usman Malik",
    email: "usman.malik@hotmail.com",
    phone: "+44 20 7946 0958",
    graduationYear: "2021",
    department: "Software Engineering",
    currentPosition: "Data Scientist",
    company: "Facebook (Meta)",
    location: "London, UK",
    expertise: ["Data Analytics", "Python", "TensorFlow"],
    previousCompanies: [
      {
        companyName: "IBM",
        role: "Data Analyst",
        duration: { from: 2021, to: 2022 },
      },
      {
        companyName: "Teradata",
        role: "Junior Data Scientist",
        duration: { from: 2020, to: 2021 },
      },
    ],
    avatar: "UM",
  },
  {
    id: 6,
    name: "Ayesha Tariq",
    email: "ayesha.tariq@gmail.com",
    phone: "+92 321 9876543",
    graduationYear: "2016",
    department: "Business Administration",
    currentPosition: "Marketing Director",
    company: "Unilever",
    location: "Karachi, Pakistan",
    expertise: ["Digital Marketing", "Brand Strategy", "Analytics"],
    previousCompanies: [
      {
        companyName: "Nestle",
        role: "Marketing Manager",
        duration: { from: 2018, to: 2020 },
      },
      {
        companyName: "P&G",
        role: "Brand Executive",
        duration: { from: 2016, to: 2018 },
      },
      {
        companyName: "P&G",
        role: "Brand Executive",
        duration: { from: 2016, to: 2018 },
      },
      {
        companyName: "P&G",
        role: "Brand Executive",
        duration: { from: 2016, to: 2018 },
      },
      {
        companyName: "P&G",
        role: "Brand Executive",
        duration: { from: 2016, to: 2018 },
      },
    ],
    avatar: "AT",
  },
  {
    id: 7,
    name: "Bilal Ahmed",
    email: "bilal.ahmed@protonmail.com",
    phone: null,
    graduationYear: "2019",
    department: "Computer Engineering",
    currentPosition: "Cybersecurity Analyst",
    company: "Cisco",
    location: "Toronto, Canada",
    expertise: ["Network Security", "Penetration Testing", "Cryptography"],
    previousCompanies: [
      {
        companyName: "Palo Alto Networks",
        role: "Security Engineer",
        duration: { from: 2019, to: 2021 },
      },
    ],
    avatar: "BA",
  },
  {
    id: 8,
    name: "Zainab Sheikh",
    email: "zainab.sheikh@gmail.com",
    phone: "+46 70 123 4567",
    graduationYear: "2022",
    department: "Computer Science",
    currentPosition: "Frontend Developer",
    company: "Spotify",
    location: "Stockholm, Sweden",
    expertise: ["React", "TypeScript", "UI/UX"],
    previousCompanies: [],
    avatar: "ZS",
  },
  {
    id: 9,
    name: "Ali Hamza",
    email: "ali.hamza@outlook.com",
    phone: "+92 333 4567890",
    graduationYear: "2022",
    department: "Computer Science",
    currentPosition: "Backend Developer",
    company: "Spotify",
    location: "Stockholm, Sweden",
    expertise: [
      "Node.js",
      "PostgreSQL",
      "Microservices",
      "Docker",
      "Kubernetes",
    ],
    previousCompanies: [
      {
        companyName: "Folio3",
        role: "Full Stack Developer",
        duration: { from: 2020, to: 2022 },
      },
    ],
    avatar: "AH",
  },
];
